// Copies ABIs from the Foundry build into the web app: npm run abi (after `forge build`).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const names = ["Kaskad", "KaskadMC", "Guard", "MockMarket", "KaskadMCv3", "RiskOracle", "GuardV2", "MockMarketV2", "RiskVault"];

let out = "// Generated by scripts/src/export-abi.ts. Do not edit.\n";
for (const n of names) {
  const art = JSON.parse(readFileSync(join(root, "contracts", "out", `${n}.sol`, `${n}.json`), "utf8"));
  const id = n[0].toLowerCase() + n.slice(1);
  out += `\nexport const ${id}Abi = ${JSON.stringify(art.abi, null, 2)} as const;\n`;
}
writeFileSync(join(root, "web", "lib", "kaskad", "abi.ts"), out);
console.log("wrote web/lib/kaskad/abi.ts");

// The CRE workflow (cre/kaskad-risk) compiles to WASM: only the functions and events it uses.
const creItems: Record<string, string[]> = {
  Kaskad: ["bookStats", "AssetSet", "PositionsLoaded", "BookReset"],
  KaskadMCv3: ["previewWithHidden"],
  RiskOracle: ["rule", "state"],
  GuardV2: ["lastAtRisk", "recoveryDelay", "maxReportAge"],
  MockMarketV2: ["borrowPaused", "deposits"],
  RiskVault: ["flagged", "asset"],
  MockUSD: ["balanceOf"],
};
let cre = "// Generated by scripts/src/export-abi.ts (npm run abi). Do not edit.\n";
for (const [n, keep] of Object.entries(creItems)) {
  const art = JSON.parse(readFileSync(join(root, "contracts", "out", `${n}.sol`, `${n}.json`), "utf8"));
  const abi = art.abi.filter((x: { name?: string }) => x.name && keep.includes(x.name));
  const id = n[0].toLowerCase() + n.slice(1);
  cre += `\nexport const ${id}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
writeFileSync(join(root, "cre", "kaskad-risk", "abi.ts"), cre);
console.log("wrote cre/kaskad-risk/abi.ts");
