// Generated by scripts/src/export-abi.ts (npm run abi). Do not edit.

export const kaskadAbi = [
  {
    "type": "function",
    "name": "bookStats",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "collateral1e6",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "debt1e6",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "otherCollUsd",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "count",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "AssetSet",
    "inputs": [
      {
        "name": "assetId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "priceWad",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "depthUsdWad",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BookReset",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PositionsLoaded",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "added",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "length",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  }
] as const;

export const kaskadMCv3Abi = [
  {
    "type": "function",
    "name": "previewWithHidden",
    "inputs": [
      {
        "name": "s",
        "type": "tuple",
        "internalType": "struct Kaskad.Scenario",
        "components": [
          {
            "name": "assetId",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "shockBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "steps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxRoundsPerStep",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxPositions",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "oracleFeedbackBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "r",
        "type": "tuple",
        "internalType": "struct Kaskad.Result",
        "components": [
          {
            "name": "totalDebt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalCollateral",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalLiquidated",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalSeized",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "badDebt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "stuckDebt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "startPrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "finalPrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "rounds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "liquidations",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "positionsUsed",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "gasUsed",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "memoryBytes",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "log",
            "type": "tuple[]",
            "internalType": "struct Kaskad.RoundLog[]",
            "components": [
              {
                "name": "step",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "round",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "liquidations",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "priceWad",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "liquidatedDebt",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "seized",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "deficit",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          }
        ]
      },
      {
        "name": "h",
        "type": "tuple",
        "internalType": "struct KaskadMCv3.Hidden",
        "components": [
          {
            "name": "oraclePrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "spotPrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "badDebtAtSpot",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "stuckDebtAtSpot",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "hiddenBadDebt",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  }
] as const;

export const riskOracleAbi = [
  {
    "type": "function",
    "name": "rule",
    "inputs": [
      {
        "name": "assetId",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct RiskOracle.Rule",
        "components": [
          {
            "name": "enabled",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "steps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "rounds",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxPositions",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "oracleFeedbackBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "triggerShockBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "lossThresholdBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "stuckThresholdBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "ltvFloorBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "ltvCeilingBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "ltvStepBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minInterval",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "state",
    "inputs": [
      {
        "name": "assetId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "atRisk",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "recommendedLtvBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "lastPublished",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "lossBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "stuckBps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  }
] as const;

export const guardV2Abi = [
  {
    "type": "function",
    "name": "lastAtRisk",
    "inputs": [
      {
        "name": "market",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maxReportAge",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "recoveryDelay",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  }
] as const;

export const mockMarketV2Abi = [
  {
    "type": "function",
    "name": "borrowPaused",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deposits",
    "inputs": [
      {
        "name": "lender",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  }
] as const;

export const riskVaultAbi = [
  {
    "type": "function",
    "name": "asset",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "flagged",
    "inputs": [
      {
        "name": "market",
        "type": "address",
        "internalType": "contract MockMarketV2"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  }
] as const;

export const mockUSDAbi = [
  {
    "type": "function",
    "name": "balanceOf",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  }
] as const;
